export const quizConstants = {
  QUIZ_DATA_REQUEST: "QUIZ_DATA_REQUEST",
  QUIZ_DATA_SUCCESS: "QUIZ_DATA_SUCCESS",
  QUIZ_DATA_FAILURE: "QUIZ_DATA_FAILURE",
  REMOVE_QUIZ_DATA: "REMOVE_QUIZ_DATA",
};

export const gridContants = {
  GRID_DATA_REQUEST: "GRID_DATA_REQUEST",
  GRID_DATA_SUCCESS: "GRID_DATA_SUCCESS",
  GRID_DATA_FAILURE: "GRID_DATA_FAILURE",
  REMOVE_GRID_DATA: "REMOVE_GRID_DATA",
};
