export const quizConstants = {
  QUIZ_DATA_REQUEST: "QUIZ_DATA_REQUEST",
  QUIZ_INITIAL_REQUEST: "QUIZ_INITIAL_REQUEST",
  QUIZ_INITIAL_FAIL: "QUIZ_INITIAL_FAIL",
  QUIZ_ADD_TO_ANSWER: "QUIZ_ADD_TO_ANSWER",
  QUIZ_DATA_FAILURE: "QUIZ_DATA_FAILURE",
  REMOVE_QUIZ_DATA: "REMOVE_QUIZ_DATA",
};
